version: '2.1'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: portfoliotracker
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        - db
      restart: always
      ports:
        - 8080:80
      volumes:
        - /sessions